const constantDataType = {
  // For log in
  LOGINCHECK: 'LOGINCHECK',
  LOGINRESULT: 'LOGINRESULT',
  LOGINERROR: 'LOGINERROR',
  // 
  AFTERLOGEDINCHECK: 'AFTERLOGEDINCHECK',
  AFTERLOGEDINRESULT: 'AFTERLOGEDINRESULT',
  AFTERLOGEDINERROR: 'AFTERLOGEDINERROR',
  // For Store
  STORECHECK: 'STORECHECK',
  LOGEDSTORECHECK: 'LOGEDSTORECHECK',
  STORERESULT: 'STORERESULT',
  STOREERROR: 'STOREERROR',

  //Formula list
  FORMULALIST: 'FORMULALIST',
  FORMULALISTRESULT: 'FORMULALISTRESULT',
  FORMULALISTERROR: 'FORMULALISTRESULT',

  //Add NewFormula
  ADDFORMULA: 'ADDFORMULA',
  ADDFORMULARESULT: 'ADDFORMULARESULT',
  ADDFORMULAERROR: 'ADDFORMULAERROR',

  UPCOMINGAPPOINMENTS: 'UPCOMINGAPPOINMENTS',
  UPCOMINGAPPOINMENTSRESULT: 'UPCOMINGAPPOINMENTSRESULT',
  UPCOMINGAPPOINMENTSERROR: 'UPCOMINGAPPOINMENTSERROR',

  //Delete Formula
  DELETEFORMULA: 'DELETEFORMULA',
  DELETEFORMULARESULT: 'DELETEFORMULARESULT',
  DELETEFORMULAERROR: 'DELETEFORMULAERROR',

  // Get ALl tasks data
  GETALLTODAYDATA: 'GETALLTODAYDATA',
  GETALLTODAYDATARESULT: 'GETALLTODAYDATARESULT',
  GETALLTODAYERROR: 'GETALLTODAYERROR',
  // Add new Task
  POSTNEWTASK: 'POSTNEWTASK',
  POSTNEWTASKRESULT: 'POSTNEWTASKRESULT',
  POSTNEWTASKERROR: 'POSTNEWTASKERROR',
  POSTEDITTASK: 'POSTEDITTASK',
  POSTEDITTASKRESULT: 'POSTEDITTASKRESULT',

  // Get All Clients data
  GETALLCLIENTS: 'GETALLCLIENTS',
  GETALLCLIENTSRESULT: 'GETALLCLIENTSRESULT',
  GETALLCLIENTSERROR: 'GETALLCLIENTSERROR',

  // Get Sales Data
  GETSALES: 'GETSALES',
  GETSALESRESULT: 'GETSALESRESULT',
  GETSALESERROR: 'GETSALESERROR',

  // Get TimeSheet data
  GETTIMESHEETDATA: 'GETTIMESHEETDATA',
  GETTIMESHEETDATARESULT: 'GETTIMESHEETDATARESULT',
  GETTIMESHEETDATAERROR: 'GETTIMESHEETDATAERROR',

  TESTDATACOUNT: 'TESTDATACOUNT',

  // Clock
  STARTCLOCK: 'STARTCLOCK',
  BREAKRETURN: 'BREAKRETURN',
  CLOCKUPDATED: 'CLOCKUPDATED',
  CLOCKACTIVITORNOW: 'CLOCKACTIVITORNOW',
  CLOCKREALTIMEDATA: 'CLOCKREALTIMEDATA',

  // Get card open details
  GETOPENCARDINFO: 'GETOPENCARDINFO',
  GETOPENCARDINFORESULT: 'GETOPENCARDINFORESULT',
  GETOPENCARDINFOERROR: 'GETOPENCARDINFOERROR',
  // CHECKINOUTRESULT 
  CHECKINOUTRESULT: "CHECKINOUTRESULT",
  // Break 
  BREAKROFFON: 'BREAKROFFON',
  BREAKROFFONRESULT: 'BREAKROFFONRESULT',
  BREAKROFFONERROR: 'BREAKROFFONERROR',

  GETREALTIMEREFRSH: 'GETREALTIMEREFRSH',
  GETREALTIMEREFRSHFINAL: 'GETREALTIMEREFRSHFINAL',

  //Past Appoinments
  PASTAPPOINMENTS: 'PASTAPPOINMENTS',
  PASTAPPOINMENTSRESULT: ' PASTAPPOINMENTSRESULT',
  PASTAPPOINMENTSERROR: ' PASTAPPOINMENTSERROR',

  // Get All Chat About
  ABOUTCHAT: 'ABOUTCHAT',

  // Get today time details
  GETTODAYWORKTIME: 'GETTODAYWORKTIME',
  GETTODAYWORKTIMERESULT: 'GETTODAYWORKTIMERESULT',
  GETTODAYWORKTIMEERROR: 'GETTODAYWORKTIMEERROR',

  // Get Book Data 
  GETBOOKDATA: 'GETBOOKDATA',
  GETBOOKDATARESULT: 'GETBOOKDATARESULT',
  GETBOOKDATAERROR: 'GETBOOKDATAERROR',

  // Get Profile info
  GETPROFILEINFO: 'GETPROFILEINFO',
  GETPROFILEINFORESULT: 'GETPROFILEINFORESULT',
  GETPROFILEINFOERROR: 'GETPROFILEINFOERROR',

  // Put clock in reminder
  PUTCLOCKINREMINDER: 'PUTCLOCKINREMINDER',

  // Get Technician info
  GETPRODUCT: 'GETPRODUCT',
  GETPRODUCTRESULT: 'GETPRODUCTRESULT',
  GETPRODUCTERROR: 'GETPRODUCTERROR',

};

export default constantDataType;
